### ISSUE TITLE
Install and anaconda-

### ISSUE THREAD

**Issue by Lesaffrea** [maju116/platypus#69]
Hi Maju,

when install platypus I have the following message 

Error: Installation of TensorFlow not found.  .... 

Have install tensorflow with anaconda therefore tensorflow is not in /usr/bin/python.   The installation of tensorflow was done with:  method = 'conda', envname = 'r-reticulate'. 

Do you have any flags which as in tensorflow will allow anaconda environment?

Thanks a lot

Alain

**Comment by alefjonathan29** [comment]
Hi,
I had this problem. I suggest you run the following commands:

install.packages("keras")
install.packages("tensorflow")

library(keras)
library(tensorflow)

install_keras()
install_tensorflow()

**Comment by Lesaffrea** [comment]
Thanks,
I love it with Rstudio 1.4 set the default Python to anaconda.
Alain
