### ISSUE TITLE
impossible to install platypus packages on R studio

### ISSUE THREAD

**Issue by nicnic91** [maju116/platypus#92]
Hello,
I tried to install platypus package on R studio, version 1.4.1106, but R give me these error:
Error in utils::download.file(url, path, method = method, quiet = quiet,  : impossibile aprire URL 'https://api.github.com/repos/maju116/platypus/tarball/HEAD'.
Thanks.

Nicola

**Comment by maju116** [comment]
can you give me the command that you used for installation? @nicnic91
